export const ADD_PHOTO_CARD = 'ADD_PHOTO_CARD';
export const EDIT_PHOTO_CARD = 'EDIT_PHOTO_CARD'
export const DELETE_PHOTO_CARD = 'DELETE_PHOTO_CARD';
export const FETCH_PHOTO_CARDS = 'FETCH_PHOTO_CARDS';
